---
- name: Example AWS Operations playbook
  hosts: localhost
  vars:
    key_name: "anshul-test"
  roles:
    - role: aws.aws_operations.run
  tasks:
    - ansible.builtin.include_role:
        name: aws.aws_operations.run
